version: "3"

services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PGDATA=${POSTGRES_DATA}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:${POSTGRES_DATA}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_HOST=${PGADMIN_HOST}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    volumes:
      - pgadmin-data:${PGADMIN_DATA}
    networks:
      - internal

  minio:
    image: bitnami/minio:2024.10.2
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_DEFAULT_BUCKETS=${MINIO_BUCKET_NAME}
      - MINIO_HOST=${MINIO_HOST}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio-data:${MINIO_DATA}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${MINIO_HOST}:${MINIO_PORT}/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:bookworm
    restart: always
    environment:
      - REDIS_DATABASE=${REDIS_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TTL_STATE=${REDIS_TTL_STATE}
      - REDIS_TTL_DATA=${REDIS_TTL_DATA}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:${REDIS_DATA}
    networks:
      - internal

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local

networks:
  internal:
    driver: bridge